# Generated by Django 3.0.7 on 2020-06-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('date_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
