# Generated by Django 3.0.7 on 2020-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='member_images')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('fb', models.URLField(null=True)),
                ('ln', models.URLField(null=True)),
            ],
        ),
    ]
